### PR TITLE
new scripts for generating picklists

### PR DESCRIPTION
**Pull request by CalixTang**
Adds in 2 scripts in ai-through-symbiosis/scripts:

- generate_picklist.py, which generates all possible combinations of (pick item, bin number) tuples for up to N pick actions and up to P permutations
- choose_picklists.py, which does random sampling from a text file, preferably from the output of generate_picklist

Adds in the 10 current pick colors in a txt file as well as the possible picklists from those 10 from at most 4 picks and at most 12 permutations.

### CODE REVIEW

**Comment by czming** [comment]
is this to generate random picklists for the dataset collection process? i.e. nothing to do with the data after it has been collected

**Comment by CalixTang** [comment]
yep, only so we randomly generate picklists to capture on the gopro

**Comment by czming** [comment]
LGTM, please pull and resolve merge conflicts if any, thanks (apologies for the delay)

**Comment by CalixTang** [comment]
Ok, merging now

**Pull request merged**
